version: "3.7"

services: 
    database_boatme:
        image: postgres
        container_name: database_boatme
        restart: always
        ports: 
            - 5432:5432
        environment: 
            - POSTGRES_USER=docker
            - POSTGRES_PASSWORD=boatme
            - POSTGRES_DB=boatme
        volumes:
            - pgdata:/data/postgres
    app:
        build: .
        container_name: boatme
        ports: 
            - 3333:3333
        volumes: 
            - .:/usr/app
        links:
            - database_boatme
        depends_on: 
            - database_boatme
        

volumes:
    pgdata:
        driver: local