version: "3.7"

services: 
    database_boatme:
        image: postgres
        container_name: database_boatme
        restart: always
        ports: 
            - $TYPEORM_PORT:$TYPEORM_PORT
        environment: 
            - POSTGRES_USER=$TYPEORM_USERNAME
            - POSTGRES_PASSWORD=$TYPEORM_PASSWORD
            - POSTGRES_DB=$TYPEORM_DATABASE
        volumes:
            - pgdata:/data/postgres
    app:
        build: .
        container_name: boatme
        ports: 
            - $APP_PORT:$APP_PORT
        volumes: 
            - .:/usr/app
        links:
            - database_boatme
        depends_on: 
            - database_boatme
        

volumes:
    pgdata:
        driver: local